### ISSUE TITLE
Lower versions of Chrome does not work

### ISSUE THREAD

**Issue by weblol** [gronxb/webview-bridge#50] opened 2024-06-25 07:24 UTC
Thank you for your work！
In lower versions of Chrome (such as Chrome 62)，bridge does not work。

Print Information：
1、bridge.isWebViewBridgeAvailable is always false
2、window.__bridgeMethods__ is also undefined

**Comment by gronxb** [comment] 2024-06-25 07:29
Hello. In what situations might someone use an older version of Chrome?

Is it using old Android devices?

**Comment by weblol** [comment] 2024-06-25 08:15
> Hello. In what situations might someone use an older version of Chrome?
> 
> Is it using old Android devices?

Yes, our users' Android devices may still be Android 8 or Android 9, and the built-in webview version is chrome62-69

**Comment by gronxb** [comment] 2024-06-26 15:46
@weblol 

https://github.com/react-native-webview/react-native-webview/pull/1099#issuecomment-645219546

It seems to be related to the issue. Although it has been a while, the matter is not yet fully resolved.
`webview-bridge` uses `injectedJavaScriptBeforeContentLoaded` in WebView to inject usable methods. 

I have confirmed that this does not work properly in older versions of Chrome.
I will consider an alternative solution as soon as possible.

**Comment by gronxb** [comment] 2024-06-30 09:30
@weblol 

The issue where the connection between native and web was not seamless has been resolved by adding a logic to rehydrate when necessary. The testing has been completed on Android 8, and it is confirmed to be functioning correctly. Please check version 1.5.1.

**Closed by gronxb** 2024-06-30 09:30 UTC
Labels: help wanted

**Comment by weblol** [comment] 2024-07-01 05:30
> @weblol
> 
> The issue where the connection between native and web was not seamless has been resolved by adding a logic to rehydrate when necessary. The testing has been completed on Android 8 (Chrome 58), and it is confirmed to be functioning correctly. Please check version 1.5.1.

Thank you very much, your work solved my problem.
